### ISSUE TITLE
Hangs on testfile

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#11]
на первом слове "record" ставим атр1.- не выделяем.
все виснет.
[controls.zip](https://github.com/iRamSoft/cuda_color_text/files/1736913/controls.zip)

**Comment by Alexey-T** [comment]
если выделить, не виснет.

**Comment by iRamSoft** [comment]
Занятно, надо править...

**Comment by Alexey-T** [comment]
см PullReq

**Comment by iRamSoft** [comment]
+ Правки от себя тоже залил
