### ISSUE TITLE
plugin for Cud

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#21]
Может ты хочешь написать плаг который выводит в сайдбар панель Explorer, с папками-файлами? под Вин надо еще сдедать комбобокс для выбора диска c: d:.... 
https://www.editplus.com/screen.html
@iRamSoft

**Comment by iRamSoft** [comment]
Привет!
Я думал в Cuda это уже есть.
Тебе на чистом питоне надо?

**Comment by iRamSoft** [comment]
И ты именно плагин хочешь? А реализацию прямо в Cuda не рассматриваешь?

**Comment by Alexey-T** [comment]
Плагин- я стараюсь все выносить в плагины, и по скорости будет одно и то же.
на чистом - это как.

**Comment by iRamSoft** [comment]
> на чистом - это как.

Без всяких вспомогательных утилит.

**Comment by Alexey-T** [comment]
На чистом- чтение папок по `os.listdir(path)`, создание формы по dlg_proc(), потом вставка формы в сайдбар через `app_proc(PROC_SIDEPANEL_nnnn)`
