### ISSUE TITLE
Save colors to .cuda-filestyles

### ISSUE THREAD

**Issue by iRamSoft** [iRamSoft/cuda_color_text#23]
miro.matas писал(а):
• is possible to save "colorized words"? (aka SynWrite to *.synw-filestyles)

**Comment by iRamSoft** [comment]
@Alexey-T , а где в Syn была такая возможность?

**Comment by Alexey-T** [comment]
![syn](https://user-images.githubusercontent.com/4154978/36965122-bee41470-2069-11e8-81ae-c6c801a9efd2.png)

**Comment by Alexey-T** [comment]
"Color Text Saved" plug

**Comment by iRamSoft** [comment]
Т.е. отдельным плагином? Принято.

**Comment by Alexey-T** [comment]
Если хочешь можешь один плаг. сделал два чтобы не вешать ивенты на 1 плагин. в Куд можно подписываться на ивенты в runtime, так что можно 1 плаг

    PROC_SET_EVENTS: Subscribe plugin to events. Param text must be 4 values ";"-separated:

**Comment by Alexey-T** [comment]
Done
