### ISSUE TITLE
Contrib

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#27]
Внеси меня в контрибуторы, плис.
я сделал патчи для плагина.

**Comment by iRamSoft** [comment]
Привет!
Куда добавить?

**Comment by Alexey-T** [comment]
в опциях этого репозитория - секция "контрибуторы", там послать приглаш мне.

**Comment by iRamSoft** [comment]
Да вроде есть там.

**Comment by iRamSoft** [comment]
Добавил в Collaborators

**Comment by Alexey-T** [comment]
Tkx. удалил опцию одну- она юзалась для исх. фрагмента а он выбирается юзером, т.ч. не надо тут юзера ограничивать. вторую опцию для "слов" оставил.
