### ISSUE TITLE
show_on_map

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#28]
show_on_map=True if opt_show_on_map else Fals

Просто копируешь Булево в Булево

    show_on_map=opt_show_on_map

2) надо добавить "api=......" в install.inf

**Comment by iRamSoft** [comment]
@Alexey-T, какая версия api будет.
Там она есть, но я так понял её поднять надо.

**Comment by Alexey-T** [comment]
1.0.253
