### ISSUE TITLE
request for BoldItalic

### ISSUE THREAD

**Issue by MiroslavMatas** [iRamSoft/cuda_color_text#29]
will be possible to add BoldItalic format command?
we have Bold, we have Italic, but BoldItalic is missing…
TIA
Miro

**Comment by iRamSoft** [comment]
This is possible by specifying the styles in the configuration file. \ Settings \ cuda_color_text.ini
![image](https://user-images.githubusercontent.com/7011418/44449914-2372d200-a5f8-11e8-8388-d50fdf9b9097.png)
Result for example:
![image](https://user-images.githubusercontent.com/7011418/44449974-55843400-a5f8-11e8-98b3-1a2e37e0be08.png)

**Comment by iRamSoft** [comment]
If you clear the first color and border, it will only BoldItalic.
![image](https://user-images.githubusercontent.com/7011418/44450123-c6c3e700-a5f8-11e8-8e82-151f1296f5f7.png)

**Comment by MiroslavMatas** [comment]
true, thanks for that…
but I must to remeber that number xx is for BoldItalic
comands: Color Italic, or Color Bold are simple for remember
but I will try to acommodate for your suggestion
thanks for now
