### ISSUE TITLE
clear styles at selection

### ISSUE THREAD

**Issue by MiroslavMatas** [iRamSoft/cuda_color_text#30]
current Clear All Styles will clear all at all file…
will be possible to add new behavior? - if there are selection, clear only at selected text
TIA
Miro

**Comment by iRamSoft** [comment]
@Alexey-T, i need additional develop for formmain_py_api.inc in CT
Add pls new ID for TATMarkers.DeleteInRange(AX1, AY1, AX2, AY2: integer);

**Comment by Alexey-T** [comment]
Added this wish, cmd /clear all styles in selection/. Test it from github: 
Plugins/ AddonManager/ Install from GitHub

**Comment by Alexey-T** [comment]
@iramsoft you see it wasn’t needed

**Comment by MiroslavMatas** [comment]
works as designed
thanks a lot

**Comment by iRamSoft** [comment]
@Alexey-T, вот как... Понял. Рыл не в ту сторону, закапываю свои мысли обратно.
