### ISSUE TITLE
CudaText forum

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#31]
Привет. можешь помоч с модерацией форума, плс?
http://synwrite.sourceforge.net/forums/index.php
 пока там есть модераторы: я, kvichans.
там пишут на английском. надо отвечать на вопросы.

можешь ответить мне вв личку.
@iRamSoft

**Comment by iRamSoft** [comment]
А на форуме личка есть?

**Comment by iRamSoft** [comment]
В упор не вижу... :-( Аватар не кликабельный.

**Comment by Alexey-T** [comment]
значит ее нет. не я настраивал форум. 
можно в дискорд, или support (@) uvviewsoft.com
