### ISSUE TITLE
font color customizing is not supported?

### ISSUE THREAD

**Issue by veksha** [iRamSoft/cuda_color_text#32]
@Alexey-T @iRamSoft 

it's hard to read text with default _font color_:

![image](https://user-images.githubusercontent.com/275333/183451983-092ac5c7-240a-4aa7-8bed-a9cf955a5fce.png)

**Comment by veksha** [comment]
relevant place in the code:

https://github.com/iRamSoft/cuda_color_text/blob/2d9f6172977f5bd8feb511d5d6687091aed9342a/__init__.py#L118-L121

**Comment by iRamSoft** [comment]
Hi!
You can customize your color set for this plugin as you like.
<img width="155" alt="image" src="https://user-images.githubusercontent.com/7011418/183454550-fad00408-8e92-4196-a9c0-1655128d3698.png">
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7011418/183454737-518d33db-0926-4f97-9838-cf7d53813a82.png">

**Comment by veksha** [comment]
@iRamSoft 
Hi, thanks for the answer!

when using dark theme in CudaText it looks good! because it uses bright font color.
but if you start coloring your text while switched to Light theme, you will get dark font color. (see my first screenshot)

![image](https://user-images.githubusercontent.com/275333/183455068-8da4506a-e8a3-458a-b8f0-26108aadd1f2.png)

**Comment by iRamSoft** [comment]
@veksha 
That is why it is possible to choose the colors that you want to use.
I can pick up the colors for the light theme and attach as an example to use in the config file.

**Comment by veksha** [comment]
> That is why it is possible to choose the colors that you want to use.

background colors are fine. I don't really want to change them. only override font color.
I can make this change to code to achieve what I want:
```python
#fcolor = ed.get_prop(PROP_COLOR, COLOR_ID_TextFont)
fcolor = html_color_to_int('#fff')
```

it would be nice to have ability to do it in configuration file.

![image](https://user-images.githubusercontent.com/275333/183461164-4f2194e5-eec8-40d0-8d42-c4dd66fb13c4.png)

**Comment by Alexey-T** [comment]
@veksha Maybe make a patch to support custom font-color in config? (default should be empty string which takes color like now). me and @iRamSoft did the work long time ago, I don't remember the code.

**Comment by Alexey-T** [comment]
I suggest even bigger change. change config to have only ONE section for styles!

[style_set]
1=color_of_back,color_of_font,color_of_borders,bold_italic_underline

where empty item means 'default'.

**Comment by iRamSoft** [comment]
@Alexey-T, One Line = One Style?

**Comment by Alexey-T** [comment]
Yes

**Comment by Alexey-T** [comment]
@veksha @iRamSoft I want to rework it by myself. having the idea to support 'u' style for underline and 'U' style for all-side-borders. give me a week for this.

**Comment by Alexey-T** [comment]
reworked!
See changed readme.txt about how to configure styles now.
font_color can be changed.

**Comment by Alexey-T** [comment]
@veksha Pls test, close the issue

**Comment by veksha** [comment]
awesome work, @Alexey-T ! thanks.

1 problem:
`o (all 4 borders)` this attribute is not restored on file reopen.

and a suggestion from me to add hint to config file. something like this:
```ini
[colors]
; Format of each style is a line of comma-separated strings:
; color_background,color_font,color_border,font_styles
; Allowed chars in `font_styles` value: b (bold), i (italic), s (strikeout), u (underline), o (all 4 borders)
; example: 1=#FFFF55,#000,#000,o
```

**Comment by Alexey-T** [comment]
Update… better now?

**Comment by veksha** [comment]
yes! one more little issue.

default font color for my current dark theme is `grey`.

1. change style in config to `1=#FFFF55,#000`, for example, (this will set `black` font color)
2. apply it on some text (it will become `black` on `yellow`)
3. modify this style to `1=#FFFF55`
4. apply it to the same (!) place
5. you will see that font color will still be `black`, but I need it to be cleared, so it can be `grey` again (or another default syntax color)

**Comment by Alexey-T** [comment]
Ahhhhh, that is design of color attribs- applying of Color_none color don’t change prev color. Remedy- set some font color in plugin config

**Comment by Alexey-T** [comment]
Remedy 2– remove old fragment , then set it again

**Comment by veksha** [comment]
unfixable. OK. thanks again!
